# Generated by Django 4.2.1 on 2023-08-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Arnaba',
            new_name='sentence',
        ),
    ]
