# Generated by Django 4.2.1 on 2023-08-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0002_rename_arnaba_sentence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('state', models.CharField(choices=[('pending', 'pending'), ('injected', 'injected')], default='pending', max_length=200)),
                ('time_of_injection', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
