# Generated by Django 4.2.1 on 2023-08-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0003_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paramater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.IntegerField(default=55)),
            ],
        ),
    ]
