# Generated by Django 4.2.1 on 2023-08-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0004_paramater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paramater',
            old_name='font_size',
            new_name='value',
        ),
        migrations.AddField(
            model_name='paramater',
            name='name',
            field=models.CharField(default='gg', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
