# Generated by Django 4.2.1 on 2023-08-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0005_rename_font_size_paramater_value_paramater_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramater',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
